// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ciGKDfqapgtMVQBmmP938S
// Component: ntRoqRwDlmcK
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { useScreenVariants as useScreenVariants_6Fj7GnKse2OD } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6Fj7gnKse2oD/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ciGKDfqapgtMVQBmmP938S/projectcss
import sty from "./PlasmicSuccessStoriesCard.module.css"; // plasmic-import: ntRoqRwDlmcK/css
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: 9Qp4AnlBM4iC/icon

createPlasmicElementProxy;

export const PlasmicSuccessStoriesCard__VariantProps = new Array();

export const PlasmicSuccessStoriesCard__ArgProps = new Array(
  "image",
  "name",
  "location",
  "description",
  "tags"
);

const $$ = {};

function PlasmicSuccessStoriesCard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          image:
            "https://images.unsplash.com/photo-1611106211090-8f3c79eb8552?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGluZGlhJTIwd2VkZGluZ3xlbnwwfDF8MHx8fDA%3D",
          name: "Asha & Raj",
          location: "Mumbai, Maharastra",
          description:
            'Asha and Raj\'s glamorous Mumbai wedding was flawlessly captured, catered, and decorated, making their day unforgettable. "Everything was perfect", says Asha.',
          tags: {
            tag: [
              "DreamCapture Photography",
              "Gourmey Delights Catering",
              "Blooming Beauties"
            ]
          }
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6Fj7GnKse2OD()
  });
  return (
    <PlasmicLink__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
      platform={"react"}
    >
      <PlasmicImg__
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"auto"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"auto"}
        height={"100%"}
        loading={"lazy"}
        src={(() => {
          try {
            return $props.image;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
        width={"100%"}
      />

      <div className={classNames(projectcss.all, sty.freeBox__s3Niu)}>
        <div className={classNames(projectcss.all, sty.freeBox__e2I0V)}>
          <div className={classNames(projectcss.all, sty.freeBox__mz0Hp)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ztI4J
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.name;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wHxdx
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.location;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
          <AntdButton
            className={classNames("__wab_instance", sty.button___80Nx3)}
            size={"small"}
            type={"default"}
          >
            <Icon38Icon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />
          </AntdButton>
        </div>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__fiSto)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__uAtCr
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.description;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___7EY2I)}
          >
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $props.tags.tag;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <AntdButton
                  className={classNames("__wab_instance", sty.button__jDrI)}
                  key={currentIndex}
                  type={"primary"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___39Ioz
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return currentItem;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Button";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </AntdButton>
              );
            })}
          </Stack__>
        </Stack__>
      </div>
      <section
        data-plasmic-name={"section"}
        data-plasmic-override={overrides.section}
        className={classNames(projectcss.all, sty.section)}
      />
    </PlasmicLink__>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "svg", "section"],
  img: ["img"],
  svg: ["svg"],
  section: ["section"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSuccessStoriesCard__ArgProps,
          internalVariantPropNames: PlasmicSuccessStoriesCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSuccessStoriesCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSuccessStoriesCard";
  } else {
    func.displayName = `PlasmicSuccessStoriesCard.${nodeName}`;
  }
  return func;
}

export const PlasmicSuccessStoriesCard = Object.assign(
  // Top-level PlasmicSuccessStoriesCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    svg: makeNodeComponent("svg"),
    section: makeNodeComponent("section"),
    // Metadata about props expected for PlasmicSuccessStoriesCard
    internalVariantProps: PlasmicSuccessStoriesCard__VariantProps,
    internalArgProps: PlasmicSuccessStoriesCard__ArgProps
  }
);

export default PlasmicSuccessStoriesCard;
/* prettier-ignore-end */
